<?php

return [
    // Level 1
    [
        'level' => 1,
        'question' => 'Apa nama tulang besar yang terletak di bagian atas lengan?',
        'options' => ['Radius', 'Ulna', 'Humerus', 'Femur', 'Tibia'],
        'answer' => 'Humerus',
        'image' => null,
    ],
    [
        'level' => 1,
        'question' => 'Tulang mana yang dikenal sebagai tulang paha?',
        'options' => ['Humerus', 'Femur', 'Tibia', 'Fibula', 'Pelvis'],
        'answer' => 'Femur',
        'image' => null,
    ],
    [
        'level' => 1,
        'question' => 'Tulang belakang terdiri dari berapa banyak tulang vertebra?',
        'options' => ['24', '26', '30', '33', '38'],
        'answer' => '33',
        'image' => null,
    ],
    [
        'level' => 1,
        'question' => 'Apa nama tulang yang membentuk pergelangan tangan?',
        'options' => ['Metakarpal', 'Karpal', 'Radius', 'Ulna', 'Humerus'],
        'answer' => 'Karpal',
        'image' => null,
    ],
    [
        'level' => 1,
        'question' => 'Tulang manakah yang merupakan bagian dari tengkorak?',
        'options' => ['Mandibula', 'Sternum', 'Femur', 'Humerus', 'Fibula'],
        'answer' => 'Mandibula',
        'image' => null,
    ],
    [
        'level' => 1,
        'question' => 'Tulang yang menghubungkan lengan dengan tubuh disebut:',
        'options' => ['Clavicula', 'Scapula', 'Humerus', 'Radius', 'Ulna'],
        'answer' => 'Clavicula',
        'image' => null,
    ],
    [
        'level' => 1,
        'question' => 'Apa nama tulang yang terdapat di bagian depan tulang kaki?',
        'options' => ['Fibula', 'Tibia', 'Femur', 'Patella', 'Karpal'],
        'answer' => 'Tibia',
        'image' => null,
    ],
    [
        'level' => 1,
        'question' => 'Tulang mana yang berada di sisi luar lengan bawah?',
        'options' => ['Radius', 'Ulna', 'Humerus', 'Femur', 'Tibia'],
        'answer' => 'Radius',
        'image' => null,
    ],
    [
        'level' => 1,
        'question' => 'Apa nama bagian dari tulang belakang yang paling bawah?',
        'options' => ['Lumbar', 'Sakral', 'Servikal', 'Thorakal', 'Coccygeal'],
        'answer' => 'Coccygeal',
        'image' => null,
    ],

    // Level 2
    [
        'level' => 2,
        'question' => 'Tulang yang membentuk alas kaki disebut:',
        'options' => ['Metatarsal', 'Karpal', 'Tarsal', 'Femur', 'Patella'],
        'answer' => 'Tarsal',
        'image' => null,
    ],
    [
        'level' => 2,
        'question' => 'Tulang manakah yang berfungsi untuk melindungi jantung dan paru-paru?',
        'options' => ['Humerus', 'Sternum', 'Femur', 'Fibula', 'Tibia'],
        'answer' => 'Sternum',
        'image' => null,
    ],
    [
        'level' => 2,
        'question' => 'Tulang leher dikenal dengan nama:',
        'options' => ['Lumbar', 'Servikal', 'Sakral', 'Thorakal', 'Coccygeal'],
        'answer' => 'Servikal',
        'image' => null,
    ],
    [
        'level' => 2,
        'question' => 'Tulang mana yang berfungsi untuk menyokong tubuh saat berdiri?',
        'options' => ['Femur', 'Tibia', 'Humerus', 'Mandibula', 'Fibula'],
        'answer' => 'Femur',
        'image' => null,
    ],
    [
        'level' => 2,
        'question' => 'Tulang manakah yang berfungsi sebagai penghubung antara tulang belakang dan tulang panggul?',
        'options' => ['Femur', 'Sacrum', 'Coccyx', 'Tibia', 'Patella'],
        'answer' => 'Sacrum',
        'image' => null,
    ],
    [
        'level' => 2,
        'question' => 'Apa nama tulang yang melindungi otak?',
        'options' => ['Mandibula', 'Cranium', 'Scapula', 'Clavicula', 'Sternum'],
        'answer' => 'Cranium',
        'image' => null,
    ],
    [
        'level' => 2,
        'question' => 'Tulang penyusun jari tangan adalah:',
        'options' => ['Metakarpal', 'Falang', 'Karpal', 'Radius', 'Humerus'],
        'answer' => 'Falang',
        'image' => null,
    ],
    [
        'level' => 2,
        'question' => 'Tulang manakah yang membentuk bagian luar pergelangan kaki?',
        'options' => ['Fibula', 'Tibia', 'Femur', 'Patella', 'Tarsal'],
        'answer' => 'Fibula',
        'image' => null,
    ],

    // Level 3
    [
        'level' => 3,
        'question' => 'Apa nama tulang yang terletak di bagian belakang tengkorak?',
        'options' => ['Frontal', 'Parietal', 'Occipital', 'Temporal', 'Nasal'],
        'answer' => 'Occipital',
        'image' => null,
    ],
    [
        'level' => 3,
        'question' => 'Tulang manakah yang memiliki fungsi sebagai penghubung antara rahang bawah dan tengkorak?',
        'options' => ['Mandibula', 'Maxilla', 'Nasal', 'Zygoma', 'Sphenoid'],
        'answer' => 'Mandibula',
        'image' => null,
    ],
    [
        'level' => 3,
        'question' => 'Manakah dari berikut ini yang bukan merupakan tulang besar?',
        'options' => ['Humerus', 'Femur', 'Radius', 'Scapula', 'Karpal'],
        'answer' => 'Karpal',
        'image' => null,
    ],
    [
        'level' => 3,
        'question' => 'Tulang manakah yang terletak di antara femur dan tibia?',
        'options' => ['Fibula', 'Patella', 'Karpal', 'Metatarsal', 'Tarsal'],
        'answer' => 'Patella',
        'image' => null,
    ],
    [
        'level' => 3,
        'question' => 'Apa nama tulang yang membentuk dinding rongga dada?',
        'options' => ['Sternum', 'Clavicula', 'Scapula', 'Femur', 'Humerus'],
        'answer' => 'Sternum',
        'image' => null,
    ],
    [
        'level' => 3,
        'question' => 'Tulang mana yang berfungsi sebagai penopang tubuh saat duduk?',
        'options' => ['Femur', 'Sacrum', 'Coccyx', 'Tibia', 'Humerus'],
        'answer' => 'Coccyx',
        'image' => null,
    ],
    [
        'level' => 3,
        'question' => 'Apa nama tulang yang membentuk bagian atas rongga dada?',
        'options' => ['Clavicula', 'Scapula', 'Sternum', 'Femur', 'Rib'],
        'answer' => 'Clavicula',
        'image' => null,
    ],
    [
        'level' => 3,
        'question' => 'Tulang mana yang dapat ditemukan di bagian bawah kaki?',
        'options' => ['Radius', 'Ulna', 'Femur', 'Patella', 'Fibula'],
        'answer' => 'Fibula',
        'image' => null,
    ],
];
